# Generated by Django 5.0.8 on 2024-08-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dersnotu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tarifler",
            new_name="Notlar",
        ),
    ]
