# Generated by Django 5.0.8 on 2024-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dersnotu", "0002_rename_tarifler_notlar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notlar",
            name="resim",
            field=models.ImageField(upload_to="resim"),
        ),
    ]
