# Generated by Django 5.0.8 on 2024-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dersnotu", "0004_alter_notlar_resim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notlar",
            name="resim",
            field=models.ImageField(upload_to="resimler"),
        ),
    ]
