# Generated by Django 5.0.8 on 2024-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dersnotu", "0005_alter_notlar_resim"),
    ]

    operations = [
        migrations.AddField(
            model_name="notlar",
            name="kategori",
            field=models.ManyToManyField(to="dersnotu.kategori"),
        ),
    ]
